### ISSUE TITLE
Embedding CLASS as the cosmology module.

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#127]
This can be done; as we already wrap class as the cosmology module in nbodykit.

**Comment by sbird** [comment]
I am thinking about implementing this as part of the work to support different transfer functions. I see a few options:

1) Embed the full class as a submodule, like bigfile, etc, and call the C routines from cosmology.c. This may be too heavy-weight: we would still need the ability to initialise with an arbitrary matter power spectrum (I would need it), and we would need to decide which of class' options to make Gadget options.

2) Add a class submodule, but compile just enough of it to call the transfer function routines (we don't need C_l), based on the format of the class python wrapper's transfer function code. Call this from cosmology.c.

3) Add a python script that calls class' python wrapper (based on existing code I use) to generate transfer functions and then feed them to MP-GenIC via files and options. This is the most light-weight in terms of compiling, the easiest to implement (since it is all python) and it retains flexibility to use other transfer function codes. But - it means we have to support infrastructure to parse class' output format in C and the python code will get broken easily.

The main difference between 1) and 2) is whether we compile all of class of just some of it. I favour 2), as it makes extensions to other cosmologies much easier, without being overkill. What do you think?

**Comment by rainwoodman** [comment]
I don't particularly like 3, because writing parser is not something we are supposed to do. 

1 and 2 has no real difference. We can reuse the scripts in classylss to embed the entire class. I don't think it needs any extra dependency... I can set it up now-ish.

**Comment by sbird** [comment]
Ok, thanks. I wasn't sure how well the python scripts would translate to C. 

The feature I would like is to compute the species-dependent growth function without having to pass two transfer functions into MP-GenIC (and ideally avoid passing any transfer functions into MP-GenIC). I would like to be able to pass a matter power spectrum in still though. I will wait until you do the embedding, and then I will implement the scale-dependent growth function stuff (or you can if you find the time, or prefer to)

**Comment by rainwoodman** [comment]
The python scripts doesn't really do much of the installation (the installation is a shell script. We still have to write C wrappers to call the correct class routines.

**Comment by rainwoodman** [comment]
A problem is that class requires several data files to run.. how do we deal with that?

**Comment by rainwoodman** [comment]
See #197 .

We probably need to introduce installation prefix to MP-Gadget at this point to deal with these 'default' files.
We already depend on a few data files (e.g. reionization table) anyways.

But parallel IO due to reading of these files will be messy. I guess we can always broadcast the results (via a TransferFunction object)

**Comment by rainwoodman** [comment]
I remember CLASS needs the files for thermal and BBN even for transfer functions.

What about approach 3 -- we can provide some python scripts that generate transfer function files. 

nbodykit/classylss computes transfer function :

http://classylss.readthedocs.io/en/stable/examples.html#density-and-velocity-transfers

**Comment by rainwoodman** [comment]
We are insulated from the file format of CLASS, because these outputs are numpy arrays. The existing array parser would work. Or we can even write these to a bigfile / hdf5 and read...

**Comment by sbird** [comment]
If we are to add radiation perturbations to our code, whatever we do can't be isolated to MP-GenIC, but has to be in MP-Gadget as well, and has to be redshift dependent, because the radiation perturbations can't be easily evolved with a growth function. So if we had a bigfile in different redshift bins we would need to load it and do interpolation.

We also want to support the case of a theorist who has a class (or camb) modification and wants to run a simulation with it as the input power spectrum.

Probably full embedding of class is more flexible (and allows us to eventually remove a lot of cosmology.h if we want), but if we have to embed the internal data structures of class into gadget or patch class we lose a lot of the benefits.

**Comment by sbird** [comment]
class does take a non-zero time to run, if you use high accuracy and massive neutrinos - so it might be better to pre-compute the transfer functions into a table. We would have to ensure we re-computed them for every cosmology change.

**Comment by rainwoodman** [comment]
"class does take a non-zero time to run", but it is coded in a way such that after the initial cost the later calls are from a fast interpolation. 

Embedding class: 
 - require data files to run; need a policy about default path and installation of data files; (which we already need a solution)
 - a parameter file translation layer to convert MP-Gadget to class; not exactly the most pleasent thing to write in C, but can be done.

Not embedding class (w classylss): 
 - deal with a large linear interpolation table. 1e4 modes times 1e3 redshifts = 1e7 ~ 40 MB in size; and errors associated with that.
 - less code in MP-Gadget/MP-GenIC
 - classylss does not encourage a workflow modifying class -- but it shall be fixed.
 - additional workflow step for the simulation set up. We already have to do this for the power spectrum, and it is inconsistent with the parameter files.

What about we instead bundle classylss directly (which doesn't require MPI), and provide a python script that parses the MP-Gadget parameter file, and produces a cosmology data file that can be used by libgadget to provide interpolated version of hubble, growth factor, transfer function and powerspectrum computed from class? The script can also take a powerspectrum.txt or a transfer.txt.

This seem to do the cut relatively cleanly?

**Comment by sbird** [comment]
That is not a bad idea. My only worry is that maintaining the python script and the code to load and interpolate the cosmology data is going to be a bit painful. How about we try this with just the transfer function/growth factor used in MP-GenIC first, so that if this turns out to be a bad idea it is easier to change course?

**Comment by sbird** [comment]
For the IC we need the (scale-dependent) derivative of the growth function, rather than the absolute value, and the species-dependent power spectra. Also the linear theory neutrino transfer function for kspace-neutrino

If we want to implement radiation perturbations into MP-Gadget then we need the radiation transfer function/perturbations interpolated by time, but that can wait.

**Comment by rainwoodman** [comment]
You want the full derivative against which?

**Comment by rainwoodman** [comment]
log a?

**Comment by sbird** [comment]
We want d ln D(a) / d ln a, called F_Omega(a) at the moment, but scale-dependent.

**Comment by rainwoodman** [comment]
I am asking about the transfer function time derivatives. I recall you can
either compute them from the potential derivative or numerically from
adjacent time steps.

**Comment by sbird** [comment]
Yes. I think numerically from adjacent time steps is easier and just as accurate. d log a.

**Comment by sbird** [comment]
We did this with #202
