### ISSUE TITLE
Integration of halo finder

### ISSUE THREAD

**Issue by pelahi** [MP-Gadget/MP-Gadget#284]
Hello, I am the author of [VELOCIraptor halo finder](www.github.com/pelahi/VELOCIraptor-STF) and would be interested in integrating the code with MP-Gadget for on-the-fly halo finding. I would also like to revert back to HDF5 (since we don't plan on writing many snapshots). How difficult would it be to revert back to HDF5?

Note that the code can already be compiled as a library and has existing infrastructure to be called from c nbody codes (specifically SWIFTSIM).

**Comment by sbird** [comment]
Hello! We would be happy to integrate Velociraptor into MP-Gadget. It would be nice to have a subhalo finder which is completely integrated. It shouldn't be too difficult, if it already has library integration. Perhaps best to hide it behind a compile-time flag, at least at first.

We're not interested in reverting back to HDF5: it would be kind of messy, and since it wouldn't be the default output format likely to be a constant source of bugs. 

It would also be less useful than you think, because our snapshots aren't compatible with P-Gadget3 anyway. If you really need hdf5 output there is a python script that converts our snapshots to something P-Gadget3 can read, and that is much easier to maintain than the HDF5 C code.

That is for the snapshots. For the output of the halo finder, we would have to think about it. If the code already exists in velociraptor it may make sense to keep with HDF5, depending on how much work porting it to bigfile is, how large the catalogues are, and how many existing scripts using that format there are. @rainwoodman what do you think?

**Comment by pelahi** [comment]
@sbird @rainwoodman currently VR can output stuff in ascii (not really useful for big runs), binary (again not that useful) and HDF5 and even has hooks for ADIOS. My preference is for HDF5 since it is a self-describing binary format that people are pretty familiar with for (sub)halo catalogs. 

Can you describe the issues you've been having with HDF5, bug wise? Is it the changing API? issues with parallel HDF5? I think so long as there is a way of converting snapshots to/from bigfile/HDF5 it isn't an issue. How are the restart files structured? Can the code also restart from a bigfile snapshot?

**Comment by sbird** [comment]
We are not concerned about bugs in HDF5. The concern is that if we had two output routines in MP-Gadget only one would get tested. So if we, for example, added an extra output array to MP-Gadget the HDF5 output might not work correctly. The reason we switched from HDF5 to bigfile was scalability at 10^5 ranks, which HDF5 was not good enough at. bigfile is a similarly self-describing format, read in practice by a python module with a very similar interface to HDF5. Depending on the level of integration, we could set up VR either to save it's internal data to a bigfile catalogue with the snapshots or to an HDF5 dataset. There is a conversion python script so it isn't much of a problem.

There are no restart files: MP-Gadget restarts with no loss of accuracy from bigfile snapshots.

**Comment by pelahi** [comment]
I am happy to have VR output to bigfile formats given there are python interfaces to the format. I personally wouldn't have time to write the code but its likely a trivial if time consuming task to add the interface to the code. 

Regarding restarts, how is it you restart with no issues from bigfile snapshots? Does this mean that the bigfile snapshot saves times for each particle to become active along with the tree? Otherwise, the tree, which typically does not need to be rebuilt at every step, will be built then, changing ever so slightly the forces calculated.

**Comment by sbird** [comment]
Why don't you write it outputting to HDF5 and we can add the bigfile conversion on top of the initial integration? It doesn't need to be immediate.

**Comment by pelahi** [comment]
Sure, that sounds fine to start with. Eventually, no point in producing a file that is only there to be converted. 

I'll give a try forking MP-Gadget and see if I can include the calls to VR using SWIFTSIM like calls. Won't be immediate but good to start something. How complex is your configure script?

**Comment by sbird** [comment]
> Regarding restarts, how is it you restart with no issues from bigfile snapshots? Does this mean that the bigfile snapshot saves times for each particle to become active along with the tree? Otherwise, the tree, which typically does not need to be rebuilt at every step, will be built then, changing ever so slightly the forces calculated.

The way we do this is to only output at the end of a PM timestep, when all the particles are active anyway (more precisely, we adjust the length of the last PM timestep to fall at the desired output time). This is what all codes should be doing anyway (and I believe Volker's private gadget does it, or did during the Illustris era) because otherwise the difference between a drift and a kick timestep means that the particle velocities have to be interpolated and are thus slightly off.

So in principle because the output is synced to a PM, we do not need to store the tree, which would be rebuilt then anyway. HOWEVER - we do also rebuild the tree every timestep. Using a static tree meant we could speed up treebuild to the point where this is not that much slower, but the reason we do it is that the dynamic tree could induce horrifying force inaccuracies under some circumstances when the tree gets out of sync with where the particles actually are. This was especially true for simulations with massive neutrinos: fast-moving particles will rapidly switch tree cells and cause a virtual hang. It is also somewhat true for simulations where the baryons and dark matter are not comoving (ie, where they have different initial transfer functions). It's the kind of thing that most people don't notice because it isn't really important for forming galaxies or for the standard single-fluid CDM simulations, but it does happen to matter for several of the things I've been working on.

Illustris-era Arepo switched to doing the same thing (rebuilding the tree every timestep) after (if I remember correctly) someone ran a test simulation in which two merging galaxies exploded. In Illustris-TNG Arepo only rebuilds the active part of the tree, and we might try and do something similar at some point.

That's the war story! If the Swift people don't already know this, someone should perhaps tell them :-)

**Comment by sbird** [comment]
> I'll give a try forking MP-Gadget and see if I can include the calls to VR using SWIFTSIM like calls. Won't be immediate but good to start something. How complex is your configure script?

 Go for it! We don't have a configure script! Just an options file and not many compile time options in that. We found that it was hard to make sure all the compile time options actually worked so we just removed them.

**Comment by pelahi** [comment]
> > Regarding restarts, how is it you restart with no issues from bigfile snapshots? Does this mean that the bigfile snapshot saves times for each particle to become active along with the tree? Otherwise, the tree, which typically does not need to be rebuilt at every step, will be built then, changing ever so slightly the forces calculated.
> 
> The way we do this is to only output at the end of a PM timestep, when all the particles are active anyway (more precisely, we adjust the length of the last PM timestep to fall at the desired output time). This is what all codes should be doing anyway (and I believe Volker's private gadget does it, or did during the Illustris era) because otherwise the difference between a drift and a kick timestep means that the particle velocities have to be interpolated and are thus slightly off.
> 
> So in principle because the output is synced to a PM, we do not need to store the tree, which would be rebuilt then anyway. HOWEVER - we do also rebuild the tree every timestep. Using a static tree meant we could speed up treebuild to the point where this is not that much slower, but the reason we do it is that the dynamic tree could induce horrifying force inaccuracies under some circumstances when the tree gets out of sync with where the particles actually are. This was especially true for simulations with massive neutrinos: fast-moving particles will rapidly switch tree cells and cause a virtual hang. It is also somewhat true for simulations where the baryons and dark matter are not comoving (ie, where they have different initial transfer functions). It's the kind of thing that most people don't notice because it isn't really important for forming galaxies or for the standard single-fluid CDM simulations, but it does happen to matter for several of the things I've been working on.
> 
> Illustris-era Arepo switched to doing the same thing (rebuilding the tree every timestep) after (if I remember correctly) someone ran a test simulation in which two merging galaxies exploded. In Illustris-TNG Arepo only rebuilds the active part of the tree, and we might try and do something similar at some point.
> 
> That's the war story! If the Swift people don't already know this, someone should perhaps tell them :-)

I think swift does this, though I don't think it tries rebuilding only active part every time step.

**Comment by sbird** [comment]
Yeah, swift also does some interesting stuff with drifting the particles: 
    -D, --drift-all                   Always drift all particles even the ones
                                      far from active particles.
which would as a side effect mean they wouldn't have to rebuild the tree (because the particles haven't moved). I don't know how they make the forces work out properly, but I assume that whatever they do is accurate.

**Comment by sbird** [comment]
@pelahi How's it going with this? A few things have happened since this thread opened :)
