### ISSUE TITLE
Crash with modified TreeCool files

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#290]
We are attempting to use some modified reionisation models outside of the provided examples, but get a crash when the TreeCool file has zeroes in (I think because we end up with nans in the baryon particle properties).

We could circumvent this ourselves by setting the TreeCool files to have very small but nonzero values, but I'm not sure if you want the code to be able to handle more general TreeCool files. What do you think?

Let me know if you'd like error messages etc!

**Comment by sbird** [comment]
This should be fixed by the latest commit to the cleanups branch
https://github.com/MP-Gadget/MP-Gadget/pull/288
If you just want to change the redshift of reionization, you can do that without changing the TREECOOL by setting UVRedshiftThreshold > 0 : it will zero the UVB for all particles when z > UVRedshiftThreshold.

**Comment by sbird** [comment]
This is fixed for me.
